// Generated by gencpp from file ros_msg/workspace_info.msg
// DO NOT EDIT!


#ifndef ros_msg_MESSAGE_WORKSPACE_INFO_H
#define ros_msg_MESSAGE_WORKSPACE_INFO_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ros_msg
{
template <class ContainerAllocator>
struct workspace_info_
{
  typedef workspace_info_<ContainerAllocator> Type;

  workspace_info_()
    : space_name()  {
    }
  workspace_info_(const ContainerAllocator& _alloc)
    : space_name(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > , typename ContainerAllocator::template rebind<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::other >  _space_name_type;
  _space_name_type space_name;





  typedef boost::shared_ptr< ::ros_msg::workspace_info_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_msg::workspace_info_<ContainerAllocator> const> ConstPtr;

}; // struct workspace_info_

typedef ::ros_msg::workspace_info_<std::allocator<void> > workspace_info;

typedef boost::shared_ptr< ::ros_msg::workspace_info > workspace_infoPtr;
typedef boost::shared_ptr< ::ros_msg::workspace_info const> workspace_infoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_msg::workspace_info_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_msg::workspace_info_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ros_msg::workspace_info_<ContainerAllocator1> & lhs, const ::ros_msg::workspace_info_<ContainerAllocator2> & rhs)
{
  return lhs.space_name == rhs.space_name;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ros_msg::workspace_info_<ContainerAllocator1> & lhs, const ::ros_msg::workspace_info_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ros_msg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::ros_msg::workspace_info_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_msg::workspace_info_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_msg::workspace_info_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_msg::workspace_info_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_msg::workspace_info_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_msg::workspace_info_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_msg::workspace_info_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0cf0a300d0fd40bbe5cc433d8d43f2d1";
  }

  static const char* value(const ::ros_msg::workspace_info_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0cf0a300d0fd40bbULL;
  static const uint64_t static_value2 = 0xe5cc433d8d43f2d1ULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_msg::workspace_info_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_msg/workspace_info";
  }

  static const char* value(const ::ros_msg::workspace_info_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_msg::workspace_info_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string[] space_name\n"
;
  }

  static const char* value(const ::ros_msg::workspace_info_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_msg::workspace_info_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.space_name);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct workspace_info_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_msg::workspace_info_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_msg::workspace_info_<ContainerAllocator>& v)
  {
    s << indent << "space_name[]" << std::endl;
    for (size_t i = 0; i < v.space_name.size(); ++i)
    {
      s << indent << "  space_name[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.space_name[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ros_msg_MESSAGE_WORKSPACE_INFO_H
