// Generated by gencpp from file lifelong_backend/SaveTraj.msg
// DO NOT EDIT!


#ifndef LIFELONG_BACKEND_MESSAGE_SAVETRAJ_H
#define LIFELONG_BACKEND_MESSAGE_SAVETRAJ_H

#include <ros/service_traits.h>


#include "SaveTrajRequest.h"
#include "SaveTrajResponse.h"


namespace lifelong_backend
{

struct SaveTraj
{

typedef SaveTrajRequest Request;
typedef SaveTrajResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SaveTraj
} // namespace lifelong_backend


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::lifelong_backend::SaveTraj > {
  static const char* value()
  {
    return "7f03a997fd65550155b59b11f37b9640";
  }

  static const char* value(const ::lifelong_backend::SaveTraj&) { return value(); }
};

template<>
struct DataType< ::lifelong_backend::SaveTraj > {
  static const char* value()
  {
    return "lifelong_backend/SaveTraj";
  }

  static const char* value(const ::lifelong_backend::SaveTraj&) { return value(); }
};


// service_traits::MD5Sum< ::lifelong_backend::SaveTrajRequest> should match
// service_traits::MD5Sum< ::lifelong_backend::SaveTraj >
template<>
struct MD5Sum< ::lifelong_backend::SaveTrajRequest>
{
  static const char* value()
  {
    return MD5Sum< ::lifelong_backend::SaveTraj >::value();
  }
  static const char* value(const ::lifelong_backend::SaveTrajRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::lifelong_backend::SaveTrajRequest> should match
// service_traits::DataType< ::lifelong_backend::SaveTraj >
template<>
struct DataType< ::lifelong_backend::SaveTrajRequest>
{
  static const char* value()
  {
    return DataType< ::lifelong_backend::SaveTraj >::value();
  }
  static const char* value(const ::lifelong_backend::SaveTrajRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::lifelong_backend::SaveTrajResponse> should match
// service_traits::MD5Sum< ::lifelong_backend::SaveTraj >
template<>
struct MD5Sum< ::lifelong_backend::SaveTrajResponse>
{
  static const char* value()
  {
    return MD5Sum< ::lifelong_backend::SaveTraj >::value();
  }
  static const char* value(const ::lifelong_backend::SaveTrajResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::lifelong_backend::SaveTrajResponse> should match
// service_traits::DataType< ::lifelong_backend::SaveTraj >
template<>
struct DataType< ::lifelong_backend::SaveTrajResponse>
{
  static const char* value()
  {
    return DataType< ::lifelong_backend::SaveTraj >::value();
  }
  static const char* value(const ::lifelong_backend::SaveTrajResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // LIFELONG_BACKEND_MESSAGE_SAVETRAJ_H
