// Generated by gencpp from file lifelong_backend/SaveTrajRequest.msg
// DO NOT EDIT!


#ifndef LIFELONG_BACKEND_MESSAGE_SAVETRAJREQUEST_H
#define LIFELONG_BACKEND_MESSAGE_SAVETRAJREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace lifelong_backend
{
template <class ContainerAllocator>
struct SaveTrajRequest_
{
  typedef SaveTrajRequest_<ContainerAllocator> Type;

  SaveTrajRequest_()
    : traj_name()  {
    }
  SaveTrajRequest_(const ContainerAllocator& _alloc)
    : traj_name(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _traj_name_type;
  _traj_name_type traj_name;





  typedef boost::shared_ptr< ::lifelong_backend::SaveTrajRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::lifelong_backend::SaveTrajRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SaveTrajRequest_

typedef ::lifelong_backend::SaveTrajRequest_<std::allocator<void> > SaveTrajRequest;

typedef boost::shared_ptr< ::lifelong_backend::SaveTrajRequest > SaveTrajRequestPtr;
typedef boost::shared_ptr< ::lifelong_backend::SaveTrajRequest const> SaveTrajRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::lifelong_backend::SaveTrajRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::lifelong_backend::SaveTrajRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::lifelong_backend::SaveTrajRequest_<ContainerAllocator1> & lhs, const ::lifelong_backend::SaveTrajRequest_<ContainerAllocator2> & rhs)
{
  return lhs.traj_name == rhs.traj_name;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::lifelong_backend::SaveTrajRequest_<ContainerAllocator1> & lhs, const ::lifelong_backend::SaveTrajRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace lifelong_backend

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::lifelong_backend::SaveTrajRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lifelong_backend::SaveTrajRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lifelong_backend::SaveTrajRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lifelong_backend::SaveTrajRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lifelong_backend::SaveTrajRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lifelong_backend::SaveTrajRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::lifelong_backend::SaveTrajRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8fa3339ef49ba7d76fa3c8920c6657d2";
  }

  static const char* value(const ::lifelong_backend::SaveTrajRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8fa3339ef49ba7d7ULL;
  static const uint64_t static_value2 = 0x6fa3c8920c6657d2ULL;
};

template<class ContainerAllocator>
struct DataType< ::lifelong_backend::SaveTrajRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "lifelong_backend/SaveTrajRequest";
  }

  static const char* value(const ::lifelong_backend::SaveTrajRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::lifelong_backend::SaveTrajRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string traj_name\n"
;
  }

  static const char* value(const ::lifelong_backend::SaveTrajRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::lifelong_backend::SaveTrajRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.traj_name);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SaveTrajRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::lifelong_backend::SaveTrajRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::lifelong_backend::SaveTrajRequest_<ContainerAllocator>& v)
  {
    s << indent << "traj_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.traj_name);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LIFELONG_BACKEND_MESSAGE_SAVETRAJREQUEST_H
