// Generated by gencpp from file lifelong_backend/SetCommand.msg
// DO NOT EDIT!


#ifndef LIFELONG_BACKEND_MESSAGE_SETCOMMAND_H
#define LIFELONG_BACKEND_MESSAGE_SETCOMMAND_H

#include <ros/service_traits.h>

#include "SetCommandRequest.h"
#include "SetCommandResponse.h"


namespace lifelong_backend
{

struct SetCommand
{

typedef SetCommandRequest Request;
typedef SetCommandResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetCommand
} // namespace lifelong_backend


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::lifelong_backend::SetCommand > {
  static const char* value()
  {
    return "30e0df826447627e18129ecb5dc74cf1";
  }

  static const char* value(const ::lifelong_backend::SetCommand&) { return value(); }
};

template<>
struct DataType< ::lifelong_backend::SetCommand > {
  static const char* value()
  {
    return "lifelong_backend/SetCommand";
  }

  static const char* value(const ::lifelong_backend::SetCommand&) { return value(); }
};


// service_traits::MD5Sum< ::lifelong_backend::SetCommandRequest> should match
// service_traits::MD5Sum< ::lifelong_backend::SetCommand >
template<>
struct MD5Sum< ::lifelong_backend::SetCommandRequest>
{
  static const char* value()
  {
    return MD5Sum< ::lifelong_backend::SetCommand >::value();
  }
  static const char* value(const ::lifelong_backend::SetCommandRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::lifelong_backend::SetCommandRequest> should match
// service_traits::DataType< ::lifelong_backend::SetCommand >
template<>
struct DataType< ::lifelong_backend::SetCommandRequest>
{
  static const char* value()
  {
    return DataType< ::lifelong_backend::SetCommand >::value();
  }
  static const char* value(const ::lifelong_backend::SetCommandRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::lifelong_backend::SetCommandResponse> should match
// service_traits::MD5Sum< ::lifelong_backend::SetCommand >
template<>
struct MD5Sum< ::lifelong_backend::SetCommandResponse>
{
  static const char* value()
  {
    return MD5Sum< ::lifelong_backend::SetCommand >::value();
  }
  static const char* value(const ::lifelong_backend::SetCommandResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::lifelong_backend::SetCommandResponse> should match
// service_traits::DataType< ::lifelong_backend::SetCommand >
template<>
struct DataType< ::lifelong_backend::SetCommandResponse>
{
  static const char* value()
  {
    return DataType< ::lifelong_backend::SetCommand >::value();
  }
  static const char* value(const ::lifelong_backend::SetCommandResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // LIFELONG_BACKEND_MESSAGE_SETCOMMAND_H
