// Generated by gencpp from file lifelong_backend/SetSpaceResponse.msg
// DO NOT EDIT!


#ifndef LIFELONG_BACKEND_MESSAGE_SETSPACERESPONSE_H
#define LIFELONG_BACKEND_MESSAGE_SETSPACERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace lifelong_backend
{
template <class ContainerAllocator>
struct SetSpaceResponse_
{
  typedef SetSpaceResponse_<ContainerAllocator> Type;

  SetSpaceResponse_()
    : traj_id()  {
    }
  SetSpaceResponse_(const ContainerAllocator& _alloc)
    : traj_id(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<uint16_t, typename ContainerAllocator::template rebind<uint16_t>::other >  _traj_id_type;
  _traj_id_type traj_id;





  typedef boost::shared_ptr< ::lifelong_backend::SetSpaceResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::lifelong_backend::SetSpaceResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SetSpaceResponse_

typedef ::lifelong_backend::SetSpaceResponse_<std::allocator<void> > SetSpaceResponse;

typedef boost::shared_ptr< ::lifelong_backend::SetSpaceResponse > SetSpaceResponsePtr;
typedef boost::shared_ptr< ::lifelong_backend::SetSpaceResponse const> SetSpaceResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::lifelong_backend::SetSpaceResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::lifelong_backend::SetSpaceResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::lifelong_backend::SetSpaceResponse_<ContainerAllocator1> & lhs, const ::lifelong_backend::SetSpaceResponse_<ContainerAllocator2> & rhs)
{
  return lhs.traj_id == rhs.traj_id;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::lifelong_backend::SetSpaceResponse_<ContainerAllocator1> & lhs, const ::lifelong_backend::SetSpaceResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace lifelong_backend

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::lifelong_backend::SetSpaceResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lifelong_backend::SetSpaceResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lifelong_backend::SetSpaceResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lifelong_backend::SetSpaceResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lifelong_backend::SetSpaceResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lifelong_backend::SetSpaceResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::lifelong_backend::SetSpaceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "253fda74e4b85ab68cde63716251d365";
  }

  static const char* value(const ::lifelong_backend::SetSpaceResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x253fda74e4b85ab6ULL;
  static const uint64_t static_value2 = 0x8cde63716251d365ULL;
};

template<class ContainerAllocator>
struct DataType< ::lifelong_backend::SetSpaceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "lifelong_backend/SetSpaceResponse";
  }

  static const char* value(const ::lifelong_backend::SetSpaceResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::lifelong_backend::SetSpaceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint16[] traj_id\n"
;
  }

  static const char* value(const ::lifelong_backend::SetSpaceResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::lifelong_backend::SetSpaceResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.traj_id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetSpaceResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::lifelong_backend::SetSpaceResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::lifelong_backend::SetSpaceResponse_<ContainerAllocator>& v)
  {
    s << indent << "traj_id[]" << std::endl;
    for (size_t i = 0; i < v.traj_id.size(); ++i)
    {
      s << indent << "  traj_id[" << i << "]: ";
      Printer<uint16_t>::stream(s, indent + "  ", v.traj_id[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // LIFELONG_BACKEND_MESSAGE_SETSPACERESPONSE_H
