// Generated by gencpp from file lifelong_backend/SetSpace.msg
// DO NOT EDIT!


#ifndef LIFELONG_BACKEND_MESSAGE_SETSPACE_H
#define LIFELONG_BACKEND_MESSAGE_SETSPACE_H

#include <ros/service_traits.h>


#include "SetSpaceRequest.h"
#include "SetSpaceResponse.h"


namespace lifelong_backend
{

struct SetSpace
{

typedef SetSpaceRequest Request;
typedef SetSpaceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetSpace
} // namespace lifelong_backend


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::lifelong_backend::SetSpace > {
  static const char* value()
  {
    return "104f242f37e181a1eefaef23ab9b90f6";
  }

  static const char* value(const ::lifelong_backend::SetSpace&) { return value(); }
};

template<>
struct DataType< ::lifelong_backend::SetSpace > {
  static const char* value()
  {
    return "lifelong_backend/SetSpace";
  }

  static const char* value(const ::lifelong_backend::SetSpace&) { return value(); }
};


// service_traits::MD5Sum< ::lifelong_backend::SetSpaceRequest> should match
// service_traits::MD5Sum< ::lifelong_backend::SetSpace >
template<>
struct MD5Sum< ::lifelong_backend::SetSpaceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::lifelong_backend::SetSpace >::value();
  }
  static const char* value(const ::lifelong_backend::SetSpaceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::lifelong_backend::SetSpaceRequest> should match
// service_traits::DataType< ::lifelong_backend::SetSpace >
template<>
struct DataType< ::lifelong_backend::SetSpaceRequest>
{
  static const char* value()
  {
    return DataType< ::lifelong_backend::SetSpace >::value();
  }
  static const char* value(const ::lifelong_backend::SetSpaceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::lifelong_backend::SetSpaceResponse> should match
// service_traits::MD5Sum< ::lifelong_backend::SetSpace >
template<>
struct MD5Sum< ::lifelong_backend::SetSpaceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::lifelong_backend::SetSpace >::value();
  }
  static const char* value(const ::lifelong_backend::SetSpaceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::lifelong_backend::SetSpaceResponse> should match
// service_traits::DataType< ::lifelong_backend::SetSpace >
template<>
struct DataType< ::lifelong_backend::SetSpaceResponse>
{
  static const char* value()
  {
    return DataType< ::lifelong_backend::SetSpace >::value();
  }
  static const char* value(const ::lifelong_backend::SetSpaceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // LIFELONG_BACKEND_MESSAGE_SETSPACE_H
