// Generated by gencpp from file lifelong_backend/SetSpaceRequest.msg
// DO NOT EDIT!


#ifndef LIFELONG_BACKEND_MESSAGE_SETSPACEREQUEST_H
#define LIFELONG_BACKEND_MESSAGE_SETSPACEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace lifelong_backend
{
template <class ContainerAllocator>
struct SetSpaceRequest_
{
  typedef SetSpaceRequest_<ContainerAllocator> Type;

  SetSpaceRequest_()
    : space_name()  {
    }
  SetSpaceRequest_(const ContainerAllocator& _alloc)
    : space_name(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _space_name_type;
  _space_name_type space_name;





  typedef boost::shared_ptr< ::lifelong_backend::SetSpaceRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::lifelong_backend::SetSpaceRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetSpaceRequest_

typedef ::lifelong_backend::SetSpaceRequest_<std::allocator<void> > SetSpaceRequest;

typedef boost::shared_ptr< ::lifelong_backend::SetSpaceRequest > SetSpaceRequestPtr;
typedef boost::shared_ptr< ::lifelong_backend::SetSpaceRequest const> SetSpaceRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::lifelong_backend::SetSpaceRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::lifelong_backend::SetSpaceRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::lifelong_backend::SetSpaceRequest_<ContainerAllocator1> & lhs, const ::lifelong_backend::SetSpaceRequest_<ContainerAllocator2> & rhs)
{
  return lhs.space_name == rhs.space_name;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::lifelong_backend::SetSpaceRequest_<ContainerAllocator1> & lhs, const ::lifelong_backend::SetSpaceRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace lifelong_backend

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::lifelong_backend::SetSpaceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lifelong_backend::SetSpaceRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lifelong_backend::SetSpaceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lifelong_backend::SetSpaceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lifelong_backend::SetSpaceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lifelong_backend::SetSpaceRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::lifelong_backend::SetSpaceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cb72dcf137f4696b5f61ac678f02ead7";
  }

  static const char* value(const ::lifelong_backend::SetSpaceRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xcb72dcf137f4696bULL;
  static const uint64_t static_value2 = 0x5f61ac678f02ead7ULL;
};

template<class ContainerAllocator>
struct DataType< ::lifelong_backend::SetSpaceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "lifelong_backend/SetSpaceRequest";
  }

  static const char* value(const ::lifelong_backend::SetSpaceRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::lifelong_backend::SetSpaceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string space_name\n"
;
  }

  static const char* value(const ::lifelong_backend::SetSpaceRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::lifelong_backend::SetSpaceRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.space_name);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetSpaceRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::lifelong_backend::SetSpaceRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::lifelong_backend::SetSpaceRequest_<ContainerAllocator>& v)
  {
    s << indent << "space_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.space_name);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LIFELONG_BACKEND_MESSAGE_SETSPACEREQUEST_H
