// Generated by gencpp from file lifelong_backend/SetTraj.msg
// DO NOT EDIT!


#ifndef LIFELONG_BACKEND_MESSAGE_SETTRAJ_H
#define LIFELONG_BACKEND_MESSAGE_SETTRAJ_H

#include <ros/service_traits.h>


#include "SetTrajRequest.h"
#include "SetTrajResponse.h"


namespace lifelong_backend
{

struct SetTraj
{

typedef SetTrajRequest Request;
typedef SetTrajResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetTraj
} // namespace lifelong_backend


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::lifelong_backend::SetTraj > {
  static const char* value()
  {
    return "b9390eb52cbf1d6864e6a126bc523cc4";
  }

  static const char* value(const ::lifelong_backend::SetTraj&) { return value(); }
};

template<>
struct DataType< ::lifelong_backend::SetTraj > {
  static const char* value()
  {
    return "lifelong_backend/SetTraj";
  }

  static const char* value(const ::lifelong_backend::SetTraj&) { return value(); }
};


// service_traits::MD5Sum< ::lifelong_backend::SetTrajRequest> should match
// service_traits::MD5Sum< ::lifelong_backend::SetTraj >
template<>
struct MD5Sum< ::lifelong_backend::SetTrajRequest>
{
  static const char* value()
  {
    return MD5Sum< ::lifelong_backend::SetTraj >::value();
  }
  static const char* value(const ::lifelong_backend::SetTrajRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::lifelong_backend::SetTrajRequest> should match
// service_traits::DataType< ::lifelong_backend::SetTraj >
template<>
struct DataType< ::lifelong_backend::SetTrajRequest>
{
  static const char* value()
  {
    return DataType< ::lifelong_backend::SetTraj >::value();
  }
  static const char* value(const ::lifelong_backend::SetTrajRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::lifelong_backend::SetTrajResponse> should match
// service_traits::MD5Sum< ::lifelong_backend::SetTraj >
template<>
struct MD5Sum< ::lifelong_backend::SetTrajResponse>
{
  static const char* value()
  {
    return MD5Sum< ::lifelong_backend::SetTraj >::value();
  }
  static const char* value(const ::lifelong_backend::SetTrajResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::lifelong_backend::SetTrajResponse> should match
// service_traits::DataType< ::lifelong_backend::SetTraj >
template<>
struct DataType< ::lifelong_backend::SetTrajResponse>
{
  static const char* value()
  {
    return DataType< ::lifelong_backend::SetTraj >::value();
  }
  static const char* value(const ::lifelong_backend::SetTrajResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // LIFELONG_BACKEND_MESSAGE_SETTRAJ_H
