// Generated by gencpp from file lifelong_backend/SetTrajResponse.msg
// DO NOT EDIT!


#ifndef LIFELONG_BACKEND_MESSAGE_SETTRAJRESPONSE_H
#define LIFELONG_BACKEND_MESSAGE_SETTRAJRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace lifelong_backend
{
template <class ContainerAllocator>
struct SetTrajResponse_
{
  typedef SetTrajResponse_<ContainerAllocator> Type;

  SetTrajResponse_()
    : success(0)  {
    }
  SetTrajResponse_(const ContainerAllocator& _alloc)
    : success(0)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::lifelong_backend::SetTrajResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::lifelong_backend::SetTrajResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SetTrajResponse_

typedef ::lifelong_backend::SetTrajResponse_<std::allocator<void> > SetTrajResponse;

typedef boost::shared_ptr< ::lifelong_backend::SetTrajResponse > SetTrajResponsePtr;
typedef boost::shared_ptr< ::lifelong_backend::SetTrajResponse const> SetTrajResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::lifelong_backend::SetTrajResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::lifelong_backend::SetTrajResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::lifelong_backend::SetTrajResponse_<ContainerAllocator1> & lhs, const ::lifelong_backend::SetTrajResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::lifelong_backend::SetTrajResponse_<ContainerAllocator1> & lhs, const ::lifelong_backend::SetTrajResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace lifelong_backend

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::lifelong_backend::SetTrajResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lifelong_backend::SetTrajResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lifelong_backend::SetTrajResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lifelong_backend::SetTrajResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lifelong_backend::SetTrajResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lifelong_backend::SetTrajResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::lifelong_backend::SetTrajResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6cca7c80398b8b31af04b80534923f16";
  }

  static const char* value(const ::lifelong_backend::SetTrajResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6cca7c80398b8b31ULL;
  static const uint64_t static_value2 = 0xaf04b80534923f16ULL;
};

template<class ContainerAllocator>
struct DataType< ::lifelong_backend::SetTrajResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "lifelong_backend/SetTrajResponse";
  }

  static const char* value(const ::lifelong_backend::SetTrajResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::lifelong_backend::SetTrajResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 success\n"
;
  }

  static const char* value(const ::lifelong_backend::SetTrajResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::lifelong_backend::SetTrajResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetTrajResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::lifelong_backend::SetTrajResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::lifelong_backend::SetTrajResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LIFELONG_BACKEND_MESSAGE_SETTRAJRESPONSE_H
