// Generated by gencpp from file lifelong_backend/SetTrajRequest.msg
// DO NOT EDIT!


#ifndef LIFELONG_BACKEND_MESSAGE_SETTRAJREQUEST_H
#define LIFELONG_BACKEND_MESSAGE_SETTRAJREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace lifelong_backend
{
template <class ContainerAllocator>
struct SetTrajRequest_
{
  typedef SetTrajRequest_<ContainerAllocator> Type;

  SetTrajRequest_()
    : traj_id(0)  {
    }
  SetTrajRequest_(const ContainerAllocator& _alloc)
    : traj_id(0)  {
  (void)_alloc;
    }



   typedef uint16_t _traj_id_type;
  _traj_id_type traj_id;





  typedef boost::shared_ptr< ::lifelong_backend::SetTrajRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::lifelong_backend::SetTrajRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetTrajRequest_

typedef ::lifelong_backend::SetTrajRequest_<std::allocator<void> > SetTrajRequest;

typedef boost::shared_ptr< ::lifelong_backend::SetTrajRequest > SetTrajRequestPtr;
typedef boost::shared_ptr< ::lifelong_backend::SetTrajRequest const> SetTrajRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::lifelong_backend::SetTrajRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::lifelong_backend::SetTrajRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::lifelong_backend::SetTrajRequest_<ContainerAllocator1> & lhs, const ::lifelong_backend::SetTrajRequest_<ContainerAllocator2> & rhs)
{
  return lhs.traj_id == rhs.traj_id;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::lifelong_backend::SetTrajRequest_<ContainerAllocator1> & lhs, const ::lifelong_backend::SetTrajRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace lifelong_backend

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::lifelong_backend::SetTrajRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lifelong_backend::SetTrajRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lifelong_backend::SetTrajRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lifelong_backend::SetTrajRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lifelong_backend::SetTrajRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lifelong_backend::SetTrajRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::lifelong_backend::SetTrajRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "da6e50521522710b17a463949892195c";
  }

  static const char* value(const ::lifelong_backend::SetTrajRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xda6e50521522710bULL;
  static const uint64_t static_value2 = 0x17a463949892195cULL;
};

template<class ContainerAllocator>
struct DataType< ::lifelong_backend::SetTrajRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "lifelong_backend/SetTrajRequest";
  }

  static const char* value(const ::lifelong_backend::SetTrajRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::lifelong_backend::SetTrajRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint16 traj_id\n"
;
  }

  static const char* value(const ::lifelong_backend::SetTrajRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::lifelong_backend::SetTrajRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.traj_id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetTrajRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::lifelong_backend::SetTrajRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::lifelong_backend::SetTrajRequest_<ContainerAllocator>& v)
  {
    s << indent << "traj_id: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.traj_id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LIFELONG_BACKEND_MESSAGE_SETTRAJREQUEST_H
